/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"

#include "bar_alpha.h"
#include "bar_alternativetags.h"
#include "bar_anybar.h"
#include "bar_dwmblocks.h"
#include "bar_ewmhtags.h"
#include "combo.h"
#include "bar_ltsymbol.h"
/* #include "bar_status.h" */
#include "bar_status2d.h"
#include "bar_statusbutton.h"
#include "bar_statuscmd.h"
#include "bar_tags.h"
#include "bar_wintitle.h"
#include "bar_layoutmenu.h"

/* Other patches */
#include "attachx.h"
#include "cfacts.h"
#include "cool_autostart.h"
#include "cyclelayouts.h"
#include "dragcfact.h"
#include "dragmfact.h"
#include "fakefullscreenclient.h"
#include "floatpos.h"
#include "focusdir.h"
#include "fullscreen.h"
#include "inplacerotate.h"
#include "ipc.h"
#include "ipc/ipc.h"
#include "ipc/util.h"
#include "moveresize.h"
#include "movestack.h"
#include "pertag.h"
#include "placemouse.h"
#include "restartsig.h"
#include "riodraw.h"
#include "rotatestack.h"
#include "scratchpads.h"
#include "selfrestart.h"
#include "shiftviewclients.h"
#include "sticky.h"
#include "swallow.h"
#include "swapfocus.h"
#include "tagothermonitor.h"
#include "tapresize.h"
#include "togglefullscreen.h"
#include "vanitygaps.h"
#include "zoomswap.h"
#include "xrdb.h"
/* Layouts */
#include "layout_centeredmaster.h"
#include "layout_columns.h"
#include "layout_deck.h"
#include "layout_fibonacci.h"
#include "layout_gapplessgrid.h"
#include "layout_horizgrid.h"
#include "layout_monocle.h"
#include "layout_tile.h"

