/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"

#include "bar_alpha.c"
#include "bar_alternativetags.c"
#include "bar_anybar.c"
#include "bar_dwmblocks.c"
#include "bar_ewmhtags.c"
#include "combo.c"
#include "bar_ltsymbol.c"
/* #include "bar_status.c" */
#include "bar_status2d.c"
#include "bar_statusbutton.c"
#include "bar_statuscmd.c"
#include "bar_tags.c"
#include "bar_wintitle.c"
#include "bar_layoutmenu.c"

/* Other patches */
#include "attachx.c"
#include "cfacts.c"
#include "cool_autostart.c"
#include "cyclelayouts.c"
#include "dragcfact.c"
#include "fakefullscreenclient.c"
#include "floatpos.c"
#include "focusdir.c"
#include "fullscreen.c"
#include "inplacerotate.c"
#include "ipc.c"
#ifdef VERSION
#include "ipc/IPCClient.c"
#include "ipc/yajl_dumps.c"
#include "ipc/ipc.c"
#include "ipc/util.c"
#endif
#include "moveresize.c"
#include "movestack.c"
#include "pertag.c"
#include "placemouse.c"
#include "restartsig.c"
#include "riodraw.c"
#include "rotatestack.c"
#include "scratchpads.c"
#include "selfrestart.c"
#include "shiftviewclients.c"
#include "sticky.c"
#include "swallow.c"
#include "swapfocus.c"
#include "tagothermonitor.c"
#include "tapresize.c"
#include "togglefullscreen.c"
#include "vanitygaps.c"
#include "zoomswap.c"
#include "xrdb.c"
#include "dragmfact.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_centeredmaster.c"
#include "layout_columns.c"
#include "layout_deck.c"
#include "layout_fibonacci.c"
#include "layout_gapplessgrid.c"
#include "layout_horizgrid.c"
#include "layout_monocle.c"
#include "layout_tile.c"

